package cn.edu.usts.pojo;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptno
     *
     * @mbg.generated Thu Jan 30 17:28:28 CST 2020
     */
    private Integer deptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dname
     *
     * @mbg.generated Thu Jan 30 17:28:28 CST 2020
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.db_source
     *
     * @mbg.generated Thu Jan 30 17:28:28 CST 2020
     */
    private String dbSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptno
     *
     * @return the value of dept.deptno
     *
     * @mbg.generated Thu Jan 30 17:28:28 CST 2020
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptno
     *
     * @param deptno the value for dept.deptno
     *
     * @mbg.generated Thu Jan 30 17:28:28 CST 2020
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dname
     *
     * @return the value of dept.dname
     *
     * @mbg.generated Thu Jan 30 17:28:28 CST 2020
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dname
     *
     * @param dname the value for dept.dname
     *
     * @mbg.generated Thu Jan 30 17:28:28 CST 2020
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.db_source
     *
     * @return the value of dept.db_source
     *
     * @mbg.generated Thu Jan 30 17:28:28 CST 2020
     */
    public String getDbSource() {
        return dbSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.db_source
     *
     * @param dbSource the value for dept.db_source
     *
     * @mbg.generated Thu Jan 30 17:28:28 CST 2020
     */
    public void setDbSource(String dbSource) {
        this.dbSource = dbSource == null ? null : dbSource.trim();
    }
}