server:
  port: 80
spring:
  application:
    name: springcloud-consumer-dept-feign-80
eureka:
  client:
    # fetch-registry: false 获取服务是服务消费者的基础，所以必须确保 eureka.client.fetch-registry=true 参数没有被修改成false。
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7002.com:7002/eureka,http://eureka-7003.com:7003/eureka
