
server:
  port: 7001
eureka:
  instance:
    hostname: eureka-7001.com
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false



